import { Timestamp } from "firebase/firestore";

// User model
export interface User {
  uid: string;
  email: string;
  displayName: string;
  phone?: string;
  phoneVerified: boolean;
  language: "fr" | "en" | "ar";
  notificationFrequency: "daily" | "weekly" | "alerts_only" | "none";
  subscription: "free" | "pro";
  subscriptionId?: string;
  subscriptionStatus?: "active" | "cancelled" | "paused" | "expired" | "refunded";
  onboardingCompleted?: boolean;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  // WhatsApp settings for Cloud Functions
  settings?: UserSettings;
}

// User settings for notifications
export interface UserSettings {
  whatsappNumber?: string;
  whatsappVerified: boolean;
  notificationFrequency: "daily" | "weekly" | "none";
  language: "fr" | "ar";
}

// Parcelle (Field) model
export interface Parcelle {
  id: string;
  userId: string;
  name: string;
  geometry: {
    type: "Polygon";
    coordinates: number[][][];
  };
  centroid: {
    lat: number;
    lng: number;
  };
  areaHectares: number;
  culture: {
    type: string;
    dateSeeding?: Timestamp;
    currentStage?: string;
  };
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// Weather data from Open-Meteo
export interface WeatherData {
  current: {
    temperature: number;
    humidity: number;
    precipitation: number;
    windSpeed: number;
  };
  hourly: {
    time: string[];
    temperature: number[];
    precipitation: number[];
    soilTemperature: number[];
    evapotranspiration: number[];
  };
  daily: {
    time: string[];
    temperatureMax: number[];
    temperatureMin: number[];
    precipitationSum: number[];
  };
}

// Soil data from SoilGrids
export interface SoilData {
  clay: number;
  sand: number;
  silt: number;
  ph: number;
  organicCarbon: number;
  texture: string;
}

// Elevation data from Open-Elevation
export interface ElevationData {
  elevation: number;
  slope?: number;
  aspect?: string;
}

// Data snapshot for a parcelle
export interface DataSnapshot {
  date: string;
  weather: WeatherData;
  soil: SoilData;
  elevation: ElevationData;
  fetchedAt: Timestamp;
}

// Report generated by AI
export interface Report {
  id: string;
  parcelleId: string;
  status: "ok" | "vigilance" | "alerte";
  summary: string;
  weatherForecast: string;
  recommendations: string[];
  diseaseRisk: {
    level: "low" | "medium" | "high";
    diseases: string[];
  };
  irrigationAdvice: string;
  nextActions: string[];
  createdAt: Timestamp;
  sentViaWhatsApp: boolean;
}

// Auth context types
export interface AuthState {
  user: User | null;
  loading: boolean;
  error: string | null;
}
